export * from './human-resources/points/points-controller'
export * from './incidents/incidents/incidents-controller'
export * from './intranet-sys/news/news-controller'
export * from './intranet-sys/notifications/notifications-controller'
export * from './intranet-sys/users/users-controller'
